s

diff --git a/tasks/main.yml b/tasks/main.yml
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -6687,12 +6687,23 @@
 #   changed_when: false
 #   failed_when: false
 
-- name: "CIS 6.2.3 | Ensure all groups in /etc/passwd exist in /etc/group"
+# - name: "CIS 6.2.3 | Ensure all groups in /etc/passwd exist in /etc/group"
+#   become: true
+#   ansible.builtin.shell: |
+#     for i in $(cut -s -d: -f4 /etc/passwd | sort -u ); do
+#       grep -q -P "^.*?:[^:]*:$i:" /etc/group || echo "Group $i is referenced by /etc/passwd but does not exist in /etc/group"
+#     done
+#   register: passwd_group_check
+#   changed_when: false
+#   failed_when: false
+
+- name: "CIS 6.2.4 | Ensure no duplicate UIDs exist"
   become: true
   ansible.builtin.shell: |
-    for i in $(cut -s -d: -f4 /etc/passwd | sort -u ); do
-      grep -q -P "^.*?:[^:]*:$i:" /etc/group || echo "Group $i is referenced by /etc/passwd but does not exist in /etc/group"
+    cut -f3 -d: /etc/passwd | sort -n | uniq -c | awk '$1 > 1 {print $2}' | while read -r uid; do
+      users=$(awk -F: -v n="$uid" '($3 == n) { print $1 }' /etc/passwd | xargs)
+      echo "Duplicate UID: \"$uid\" Users: \"$users\""
     done
-  register: passwd_group_check
+  register: duplicate_uids
   changed_when: false
   failed_when: false
